apiVersion: v1
kind: ConfigMap
metadata:
  name: nexacart-config
  namespace: nexacart
data:
  NODE_ENV: "production"
  PORT: "5000"
  RECOMMENDATION_PORT: "8000"
  MONGO_URI: "mongodb://mongodb-service.nexacart.svc.cluster.local:27017/nexacart"
  RECOMMENDATION_SERVICE_URL: "http://recommendation-service.nexacart.svc.cluster.local:8000"
  CLIENT_URL: "http://localhost:5173"
